language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"

matrix:
  include:
    - python: 2.7
      env: JYTHON=org.python:jython-installer:2.5.3
      # env: JYTHON=org.python:jython-installer:2.5.3 FOO=foo

before_install:
  - if [ -n "$JYTHON" ]; then ./before_install_jython.sh; source $HOME/myvirtualenv/bin/activate ;fi
  - if [ -n "$JYTHON" ]; then pip install jip==0.7; fi
  - if [ -n "$JYTHON" ]; then export CLASSPATH=$VIRTUAL_ENV/javalib/*; fi
    
script:
  - make test