language: python
python:
  - "3.6"
  - "3.7"

matrix:
  include:
    - python: 2.7
      env: JYTHON=org.python:jython-installer:2.7.1

before_install:
  - if [ -n "$JYTHON" ]; then travis_wait ./before_install_jython.sh; source $HOME/myvirtualenv/bin/activate ;fi
  - if [ -n "$JYTHON" ]; then pip install jip==0.9.13; fi
  - if [ -n "$JYTHON" ]; then export CLASSPATH=$VIRTUAL_ENV/javalib/*; fi
    
script:
  - python mframe_test.py